name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    uses: BlackHole1/fastify-workflows-community/.github/workflows/plugins-ci-pnpm.yml@v1
